imports:
- { resource: services.yml }

parameters:
  api:
      # baseUrl: https://onebip.kanbanize.com/index.php/api/kanbanize
      baseUrl: http://kanbanize.com/index.php/api/kanbanize

  display:
    tasks.longlist:
      - taskid
      - assignee
      - priority
      - lanename
      - columnname
      - title

    tasks.shortlist:
      - taskid
      - assignee
      - lanename
      - columnname
      - title
