imports:
- { resource: services.yml }

parameters:
  api:
    baseUrl: http://kanbanize.com/index.php/api/kanbanize


  display:
    tasks.longlist:
      - taskid
      - assignee
      - priority
      - lanename
      - columnname
      - title

