parameters:
  cache.yaml: 'KbizeCli\Cache\YamlCache'

services:
  httpClient:
    class: KbizeCli\Http\Client
    factory_class: KbizeCli\Http\Client
    factory_method: fromConfig
    arguments: [%api%]

  sdk:
    class: KbizeCli\Sdk\Sdk
    arguments: ["@httpClient"]

  gateway:
    class: KbizeCli\Gateway
    arguments: ["@sdk"]

  kbize:
    class: KbizeCli\Gateway
    arguments: ["@sdk", "@user"]

  user:
    class: KbizeCli\User
    factory_class: KbizeCli\User
    factory_method: fromCache
    arguments: ["@userCache"]

  yamlParser:
    class: Symfony\Component\Yaml\Parser
    arguments: [2]

  yamlDumper:
    class: Symfony\Component\Yaml\Dumper

  userCache:
    class: '%cache.yaml%'
    arguments: ['data/env/user.yml', '@yamlParser', '@yamlDumper']
